import React from 'react';
import DropDownTextInput from '../../../../components/dropDownTextInput/DropDownTextInput';
import Accumulator from '../../../../components/accumulator/Accumulator';
import {BottomSection, Container, Content, Paragraph, Section, Spacer, SubSection, TopSection} from '../style/style';
import {useTranslation} from 'react-i18next';

const Flat = ({state}) => {
  const {t} = useTranslation();
  return (
    <Container>
      <Content>
        <Section>
          <TopSection>
            <Paragraph>
              {t('type-poster')}
            </Paragraph>
          </TopSection>
          <BottomSection>
            <Accumulator
              width="100%"
              hook="redux"
              type="single"
              reducer="posters"
              reduxField="typePoster"
              values={[
                'rent',
                'sale',
              ]}
            />
          </BottomSection>
        </Section>
        <Section>
          <TopSection>
            <Paragraph>
              {t('state')}
            </Paragraph>
          </TopSection>
          <BottomSection>
            <Accumulator
              width="100%"
              type="many"
              hook="redux"
              reducer="posters"
              reduxField="typeApartment"
              values={[
                'first',
                'second',
              ]}
            />
          </BottomSection>
        </Section>
        <Section>
          <TopSection>
            <Paragraph>
              {t('wall-material')}
            </Paragraph>
          </TopSection>
          <BottomSection>
            <Accumulator
              width="100%"
              type="many"
              hook="redux"
              reducer="posters"
              reduxField="wallMaterial"
              values={[
                'cube',
                'panel',
                'monolith',
                'block',
                'other',
              ]}
            />
          </BottomSection>
        </Section>
        <Section>
          <TopSection>
            <Paragraph>
              {t('count-rooms')}
            </Paragraph>
          </TopSection>
          <BottomSection>
            <Accumulator
              width="100%"
              type="many"
              hook="redux"
              reducer="posters"
              reduxField="countRooms"
              values={[
                '1',
                '2',
                '3',
                '4',
                '5',
                '6+',
              ]}
            />
          </BottomSection>
        </Section>
        <Section>
          <TopSection>
            <Paragraph>
              {t('price')}
            </Paragraph>
          </TopSection>
          <BottomSection>
            <SubSection>
              <DropDownTextInput
                width="45%"
                height="30px"
                disabledDrop
                placeholder="from"
                unit="руб"
                hook="redux"
                reducer="posters"
                reduxField="priceFrom"
                label="from"
              />
              <Spacer/>
              <DropDownTextInput
                width="45%"
                height="30px"
                disabledDrop
                unit="руб"
                placeholder="to"
                hook="redux"
                reducer="posters"
                reduxField="priceTo"
                label="to"
              />
            </SubSection>
          </BottomSection>
        </Section>
        <Section>
          <TopSection>
            <Paragraph>
              {t('area')}
            </Paragraph>
          </TopSection>
          <BottomSection>
            <SubSection>
              <DropDownTextInput
                width="45%"
                disabledDrop
                height="30px"
                placeholder="from"
                hook="redux"
                reducer="posters"
                reduxField="areaFrom"
                label="from"
                unit="м"
                sup={2}
              />
              <Spacer/>
              <DropDownTextInput
                width="45%"
                height="30px"
                disabledDrop
                placeholder="to"
                hook="redux"
                reducer="posters"
                reduxField="areaTo"
                unit="м"
                sup={2}
                label="to"
              />
            </SubSection>
          </BottomSection>
        </Section>
        <Section>
          <TopSection>
            <Paragraph>
              {t('kitchen-area')}
            </Paragraph>
          </TopSection>
          <BottomSection>
            <SubSection>
              <DropDownTextInput
                width="45%"
                height="30px"
                disabledDrop
                unit="м"
                sup={2}
                placeholder="from"
                hook="redux"
                reducer="posters"
                reduxField="kitchenAreaFrom"
                label="from"
              />
              <Spacer/>
              <DropDownTextInput
                width="45%"
                disabledDrop
                height="30px"
                unit="м"
                sup={2}
                placeholder="to"
                hook="redux"
                reducer="posters"
                reduxField="kitchenAreaTo"
                label="to"
              />
            </SubSection>
          </BottomSection>
        </Section>
        <Section>
          <TopSection>
            <Paragraph>
              {t('count-floors')}
            </Paragraph>
          </TopSection>
          <BottomSection>
            <SubSection>
              <DropDownTextInput
                width="45%"
                height="30px"
                disabledDrop
                placeholder="from"
                hook="redux"
                reducer="posters"
                reduxField="countFloorsFrom"
                label="from"
              />
              <Spacer/>
              <DropDownTextInput
                width="45%"
                disabledDrop
                height="30px"
                placeholder="to"
                hook="redux"
                reducer="posters"
                reduxField="countFloorsTo"
                label="to"
              />
            </SubSection>
          </BottomSection>
        </Section>
        <Section>
          <TopSection>
            <Paragraph>
              {t('floor')}
            </Paragraph>
          </TopSection>
          <BottomSection>
            <SubSection>
              <DropDownTextInput
                width="45%"
                disabledDrop
                height="30px"
                placeholder="from"
                hook="redux"
                reducer="posters"
                reduxField="countFloorFrom"
                label="from"
              />
              <Spacer/>
              <DropDownTextInput
                index={4}
                width="45%"
                height="30px"
                disabledDrop
                placeholder="to"
                hook="redux"
                reducer="posters"
                reduxField="countFloorTo"
                label="to"
              />
            </SubSection>
          </BottomSection>
        </Section>
        <Section>
          <TopSection>
            <Paragraph>
              {t('year-of-construction')}
            </Paragraph>
          </TopSection>
          <BottomSection>
            <SubSection>
              <DropDownTextInput
                width="45%"
                height="30px"
                disabledDrop
                placeholder="from"
                hook="redux"
                reducer="posters"
                reduxField="yearOfConstructionFrom"
                label="from"
              />
              <Spacer/>
              <DropDownTextInput
                width="45%"
                height="30px"
                placeholder="to"
                disabledDrop
                hook="redux"
                reducer="posters"
                reduxField="yearOfConstructionTo"
                label="to"
              />
            </SubSection>
          </BottomSection>
        </Section>
      </Content>
    </Container>
  );
};

export default Flat;
