import React from 'react';
import DropDownTextInput from '../../../../components/dropDownTextInput/DropDownTextInput';
import Accumulator from '../../../../components/accumulator/Accumulator';
import {BottomSection, Container, Content, Paragraph, Section, Spacer, SubSection, TopSection} from '../style/style';
import {useTranslation} from 'react-i18next';


const House = ({state}) => {
  const {t} = useTranslation();
  return (
    <Container>
      <Content>
        <Section>
          <TopSection>
            <Paragraph>
              {t('type-poster')}
            </Paragraph>
          </TopSection>
          <BottomSection>
            <Accumulator
              width="100%"
              type="single"
              hook="redux"
              reducer="posters"
              reduxField="typePoster"
              values={[
                'rent',
                'sale',
              ]}
            />
          </BottomSection>
        </Section>
        <Section>
          <TopSection>
            <Paragraph>
              {t('state')}
            </Paragraph>
          </TopSection>
          <BottomSection>
            <Accumulator
              width="100%"
              type="many"
              hook="redux"
              reducer="posters"
              reduxField="state"
              values={[
                'decoration',
                'not-decoration',
                'building',
              ]}
            />
          </BottomSection>
        </Section>
        <Section>
          <TopSection>
            <Paragraph>
              {t('wall-material')}
            </Paragraph>
          </TopSection>
          <BottomSection>
            <Accumulator
              width="100%"
              type="many"
              hook="redux"
              reducer="posters"
              reduxField="wallMaterial"
              values={[
                'cube',
                'block',
                'tree',
                'other',
              ]}
            />
          </BottomSection>
        </Section>
        <Section>
          <TopSection>
            <Paragraph>
              {t('price')}
            </Paragraph>
          </TopSection>
          <BottomSection>
            <SubSection>
              <DropDownTextInput
                width="45%"
                height="30px"
                disabledDrop
                placeholder="from"
                unit="руб"
                hook="redux"
                reducer="posters"
                reduxField="priceFrom"
                label="from"
              />
              <Spacer/>
              <DropDownTextInput
                width="45%"
                height="30px"
                unit="руб"
                placeholder="to"
                hook="redux"
                reducer="posters"
                reduxField="priceTo"
                label="to"
                disabledDrop
              />
            </SubSection>
          </BottomSection>
        </Section>
        <Section>
          <TopSection>
            <Paragraph>
              {t('count-rooms')}
            </Paragraph>
          </TopSection>
          <BottomSection>
            <SubSection>
              <DropDownTextInput
                width="45%"
                height="30px"
                disabledDrop
                placeholder="from"
                hook="redux"
                reducer="posters"
                reduxField="countRoomsFrom"
                label="from"
                unit="м"
                sup={2}
              />
              <Spacer/>
              <DropDownTextInput
                width="45%"
                height="30px"
                disabledDrop
                placeholder="to"
                hook="redux"
                reducer="posters"
                reduxField="countRoomsTo"
                unit="м"
                sup={2}
                label="to"
              />
            </SubSection>
          </BottomSection>
        </Section>
        <Section>
          <TopSection>
            <Paragraph>
              {t('live-area')}
            </Paragraph>
          </TopSection>
          <BottomSection>
            <SubSection>
              <DropDownTextInput
                width="45%"
                height="30px"
                disabledDrop
                placeholder="from"
                hook="redux"
                reducer="posters"
                reduxField="areaFrom"
                label="from"
                unit="м"
                sup={2}
              />
              <Spacer/>
              <DropDownTextInput
                width="45%"
                height="30px"
                disabledDrop
                placeholder="to"
                hook="redux"
                reducer="posters"
                reduxField="areaTo"
                unit="м"
                sup={2}
                label="to"
              />
            </SubSection>
          </BottomSection>
        </Section>
        <Section>
          <TopSection>
            <Paragraph>
              {t('land-area')}
            </Paragraph>
          </TopSection>
          <BottomSection>
            <SubSection>
              <DropDownTextInput
                width="45%"
                height="30px"
                unit="м"
                sup={2}
                placeholder="from"
                hook="redux"
                reducer="posters"
                reduxField="landAreaFrom"
                label="from"
                disabledDrop
              />
              <Spacer/>
              <DropDownTextInput
                width="45%"
                height="30px"
                unit="м"
                sup={2}
                placeholder="to"
                hook="redux"
                reducer="posters"
                reduxField="landAreaTo"
                label="to"
                disabledDrop
              />
            </SubSection>
          </BottomSection>
        </Section>
        <Section>
          <TopSection>
            <Paragraph>
              {t('count-floors')}
            </Paragraph>
          </TopSection>
          <BottomSection>
            <Accumulator
              width="100%"
              type="many"
              placeholder="count-floors"
              hook="redux"
              reducer="posters"
              reduxField="countFloors"
              values={[
                '1',
                '2',
                '3',
                '4',
                '5',
                '6+',
              ]}
            />
          </BottomSection>
        </Section>
        <Section>
          <TopSection>
            <Paragraph>
              {t('year-of-construction')}
            </Paragraph>
          </TopSection>
          <BottomSection>
            <SubSection>
              <DropDownTextInput
                width="45%"
                height="30px"
                placeholder="from"
                hook="redux"
                reducer="posters"
                reduxField="yearOfConstructionFrom"
                label="from"
                disabledDrop
              />
              <Spacer/>
              <DropDownTextInput
                width="45%"
                height="30px"
                placeholder="to"
                hook="redux"
                reducer="posters"
                reduxField="yearOfConstructionTo"
                label="to"
                disabledDrop
              />
            </SubSection>
          </BottomSection>
        </Section>
      </Content>
    </Container>
  );
};

export default House;
